"""add new columns for user

Revision ID: 181196cb92fa
Revises: 71c305d3021d
Create Date: 2020-06-22 15:40:28.081767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '181196cb92fa'
down_revision = '71c305d3021d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'create_time')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
