"""add my column for user activate

Revision ID: 749e2769d10c
Revises: 527bc3edb97d
Create Date: 2020-06-27 12:04:16.984462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '749e2769d10c'
down_revision = '527bc3edb97d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_activated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_activated')
    # ### end Alembic commands ###
